CREATE TABLE objetivo (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	descricao TEXT NOT NULL
);

CREATE TABLE usuario (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	senha TEXT NOT NULL,
	imc REAL NOT NULL,
	objetivo_id INTEGER NOT NULL,
	FOREIGN KEY (objetivo_id) REFERENCES objetivo(id)
);